from __future__ import annotations

from intraday_platform.domain.value_objects.timeframe import Timeframe

STARTING_CAPITAL_GBP = 100.0
COMMISSION_RATE = 0.001
MAX_POSITION_GBP = 50.0
MAX_STOCKS_PER_DAY = 5
RISK_FRACTION_PER_TRADE = 0.25
DEFAULT_TIMEFRAME = Timeframe.ONE_MINUTE
MARKET_CODE = "LSE"
CURRENCY = "GBP"
MARKET_TIMEZONE = "Europe/London"
LIQUIDITY_LOOKBACK_DAYS = 20
LIQUIDITY_MIN_AVG_DAILY_VOLUME = 100_000.0
DAILY_SELECTION_LOOKBACK_DAYS = 60
DAILY_SELECTION_RECENT_WINDOW = 5
DAILY_SELECTION_PRIOR_WINDOW = 20
DAILY_SELECTION_BREAKOUT_WINDOW = 20
DAILY_SELECTION_MAX_WORKERS = 8
OPTIMIZATION_MAX_WORKERS = 24
